#!/bin/sh -e

# $Id: setup,v 1.2 2003/03/19 05:44:22 ifindkarma Exp $

cd `dirname $0`

if [ ! -x configure ]; then
    echo "Generating configure..."
    autoconf
fi

if [ ! -f kn_config.h.in ]; then
    echo "Generating kn_config.h.in..."
    autoheader -l buildconf
fi

# End of setup
