#!/bin/sh -e

# $Id: setup,v 1.4 2003/11/14 02:03:12 bsittler Exp $

cd `dirname $0`

if [ ! -x configure ]; then
    echo "Generating configure..."
    autoconf
fi

if [ ! -f kn_config.h.in ]; then
    echo "Generating kn_config.h.in..."
    (cd buildconf && touch kn_config.h.in && autoheader ../configure.in > ../kn_config.h.in && cat kn_config.h.in >> ../kn_config.h.in || rm ../kn_config.h.in)
fi

# End of setup
